image: node:latest

stages:
  - deploy

deploy-staging:
  image: ubuntu:latest
  stage: deploy
  variables:
    WORKDIR: /var/www/web.saveplus.io
  only:
    - develop
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval `ssh-agent -s`
    - echo "$DO_DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H $DO_DEV_IP >> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no root@$DO_DEV_IP "cd $WORKDIR && git pull origin develop && yarn install && yarn build && pm2 restart all"
