export const PIN_RESET_START = "PIN_RESET_START";
export const PIN_RESET_ERROR = "PIN_RESET_ERROR";
export const PIN_RESET_SUCCESS = "PIN_RESET_SUCCESS";
export const PIN_RESET_ERROR_CLEAR = "PIN_RESET_ERROR_CLEAR";
