export const PIN_RESET_UPDATE_START = "PIN_RESET_UPDATE_START";
export const PIN_RESET_UPDATE_ERROR = "PIN_RESET_UPDATE_ERROR";
export const PIN_RESET_UPDATE_SUCCESS = "PIN_RESET_UPDATE_SUCCESS";
export const PIN_RESET_UPDATE_ERROR_CLEAR = "PIN_RESET_UPDATE_ERROR_CLEAR";
