export const GET_ALL_CAUSES_START = "GET_ALL_CAUSES_START";
export const GET_ALL_CAUSES_SUCCESS = "GET_ALL_CAUSES_SUCCESS";
export const GET_ALL_CAUSES_ERROR = "GET_ALL_CAUSES_ERROR";

export const TRANSFER_ALL_CAUSES_START = "TRANSFER_ALL_CAUSES_START";
export const TRANSFER_ALL_CAUSES_SUCCESS = "TRANSFER_ALL_CAUSES_SUCCESS";
export const TRANSFER_ALL_CAUSES_ERROR = "TRANSFER_ALL_CAUSES_ERROR";
