export const CANCEL_CAUSE_START: string = "CANCEL_CAUSE_START";
export const CANCEL_CAUSE_SUCCESS: string = "CANCEL_CAUSE_SUCCESS";
export const CANCEL_CAUSE_ERROR: string = "CANCEL_CAUSE_ERROR";
export const RESET_CANCEL_ERROR: string = "RESET_CANCEL_ERROR";
