export const CREATE_CAUSE_START = "CREATE_CAUSE_START";
export const CREATE_CAUSE_ERROR = "CREATE_CAUSE_ERROR";
export const CREATE_CAUSE_SUCCESS = "CREATE_CAUSE_SUCCESS";
export const SET_CROPPED_IMAGE = "SET_CROPPED_IMAGE";
export const CLEAR_CROPPED_IMAGE = "CLEAR_CROPPED_IMAGE";
export const CLEAR_CREATE_CAUSE = "CLEAR_CREATE_CAUSE";
