export const GET_DONORS_START = "GET_DONORS_START";
export const GET_DONORS_ERROR = "GET_DONORS_ERROR";
export const GET_DONORS_SUCCESS = "GET_DONORS_SUCCESS";

export const SEARCH_DONORS_START = "SEARCH_DONORS_START";
export const SEARCH_DONORS_ERROR = "SEARCH_DONORS_ERROR";
export const SEARCH_DONORS_SUCCESS = "SEARCH_DONORS_SUCCESS";

export const MORE_SEARCH_DONORS_START = "MORE_SEARCH_DONORS_START";
export const MORE_SEARCH_DONORS_ERROR = "MORE_SEARCH_DONORS_ERROR";
export const MORE_SEARCH_DONORS_SUCCESS = "MORE_SEARCH_DONORS_SUCCESS";

export const CLEAR_SEARCH_DONORS = "CLEAR_SEARCH_DONORS";
