export const GET_SINGLE_CAUSE_START = "GET_SINGLE_CAUSE_START";
export const GET_SINGLE_CAUSE_ERROR = "GET_SINGLE_CAUSE_ERROR";
export const GET_SINGLE_CAUSE_SUCCESS = "GET_SINGLE_CAUSE_SUCCESS";
export const RESET_SINGLE_CAUSE_ERROR = "RESET_SINGLE_CAUSE_ERROR";

export const TRANSFER_SINGLE_CAUSE_START = "TRANSFER_SINGLE_CAUSE_START";
export const TRANSFER_SINGLE_CAUSE_SUCCESS = "TRANSFER_SINGLE_CAUSE_SUCCESS";
export const TRANSFER_SINGLE_CAUSE_ERROR = "TRANSFER_SINGLE_CAUSE_ERROR";

export const CASHOUT_SINGLE_CAUSE_START = "CASHOUT_SINGLE_CAUSE_START";
export const CASHOUT_SINGLE_CAUSE_SUCCESS = "CASHOUT_SINGLE_CAUSE_SUCCESS";
export const CASHOUT_SINGLE_CAUSE_ERROR = "CASHOUT_SINGLE_CAUSE_ERROR";
