export const GET_SINGLE_CAUSE_START = "GET_SINGLE_CAUSE_START";
export const GET_SINGLE_CAUSE_ERROR = "GET_SINGLE_CAUSE_ERROR";
export const GET_SINGLE_CAUSE_SUCCESS = "GET_SINGLE_CAUSE_SUCCESS";
export const RESET_SINGLE_CAUSE_ERROR = "RESET_SINGLE_CAUSE_ERROR";
