
export const SEND_CONFIRMATION_CODE_START = "SEND_CONFIRMATION_CODE_START";
export const SEND_CONFIRMATION_CODE_ERROR = "SEND_CONFIRMATION_CODE_ERROR";
export const SEND_CONFIRMATION_CODE_SUCCESS = "SEND_CONFIRMATION_CODE_SUCCESS";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
