export const GET_ALL_BROADCASTS_START = "GET_ALL_BROADCASTS_START";
export const GET_ALL_BROADCASTS_ERROR = "GET_ALL_BROADCASTS_ERROR";
export const GET_ALL_BROADCASTS_SUCCESS = "GET_ALL_BROADCASTS_SUCCESS";
export const CLEAR_ALL_BROADCASTS = "CLEAR_ALL_BROADCASTS";
